gameover/api/controllers/category.py
from flask import Blueprint, jsonify, request
from flask_jwt_extended import (
    get_jwt_identity,
    jwt_required,
    get_jwt
)

from gameover.domain.models.category import Category
from gameover.domain.models.user import User

bp = Blueprint('Category', __name__, url_prefix='/api')

@bp.route('/categories')
def get():
    categories = Category.query.all()
    return {
        'success': True,
        'message': 'Categorias encontradas com sucesso',
        'data': [{
            'id': category.id,
            'name': category.name,
            'created_at': category.created_at
        } for category in categories]
    }, 200

@bp.route('/categories', methods=['POST'])
@jwt_required()
def create():
    identity = get_jwt_identity()    
    user = User.query.filter_by(email=identity, is_superuser=True).one_or_none()
    if not user:
        return 'Usuário náo autorizado', 401

    try:
        body = request.get_json()
        category = Category(**body)
        category.create()
        category.commit()
        return jsonify(category), 200
    except Exception as e:
        raise e

gameover/api/controllers/doc.py
from flask import Blueprint, render_template, redirect, request

from gameover.domain.models.user import User

bp = Blueprint('Doc', __name__)

@bp.route('/')
def index():
    user = User.query.get(1)
    return render_template('index.html', title='Doc', msg='My Doc Page', user=user)

@bp.route('/login', methods=['GET', 'POST'])
def login_page():
    if request.method == 'GET':
        user = User.query.get(1)
        return render_template('login.html', title='Login', user=user)
    if request.method == 'POST':
        inputs = request.get_form()
        print(inputs)
        return redirect('/')
        

gameover/api/controllers/user.py
from flask import Blueprint, request, jsonify
from flask_jwt_extended import (
    jwt_required,
    current_user
)

from gameover.api.ext.jwt import (
    admin_required,
    superuser_required,
    user_required
)

from gameover.domain.models.user import User

bp = Blueprint('User', __name__, url_prefix='/api')

@bp.route('/users/auth', methods=['POST'])
def autheticate():
    try:
        (email, password) = (
            request.json.get('email'),
            request.json.get('password')
        )
        if not email or not password:
            return 'Os campos são obrigatórios', 422

        user = User.query.filter_by(email=email).one_or_none()
        if not user or not user.check_password(current_password=password):
            return 'E-mail ou senha inválidos', 422

        token = user.generate_access_token()
        return {
            'access_token': token
        }, 200
    except Exception as e:
        raise e

@bp.route('/users', methods=['GET','POST'])
def create():
    if request.method == 'GET':
        users = User.query.all()
        return {
            'data': [{
                'id': user.id,
                'name': user.name,
                'surname': user.surname,
                'email': user.email,
                'role': user.role,
                'password': user.password,
                'is_superuser': user.is_superuser,
                'created_at': user.created_at,
                'updated_at': user.updated_at
            } for user in users]
        }, 200

    if request.method == 'POST':
        body = request.get_json()
        if not body:
            return 'Os campos são obrigatórios', 422

        user = User(**body)
        user.add_role('user_only')
        user.insert()
        user.commit()
        return 'Usuário registrado com sucesso', 200

@bp.route('/users/<int:id>', methods=['GET', 'PUT', 'DELETE'])
def get(id):
    try:
        user = User.query.get(id)
        if request.method == 'GET':
            return {
                'data': {
                    'name': user.name
                }
            }
        if request.method == 'PUT':
            body = request.get_json()
            user.update(**body)
            user.commit()
            return {
                'id': user.id,
                'name': user.name,
                'surname': user.surname
            }, 200

        if request.method == 'DELETE':
            user.delete()
            user.commit()
            return 'Usuário deletado com sucesso', 200
    except Exception as e:
        raise e

@bp.route('/users/<int:id>/change-password', methods=['PATCH'])
def change_password(id):
    try:
        user = User.query.get(id)
        (current_password, new_password) = (
            request.json.get('current_password', None),
            request.json.get('new_password', None),
        )
        if not user.check_password(current_password):
            return 'Falha ao alterar senha', 422

        user.change_password(new_password)
        user.commit()
        return 'Senha alterada com sucesso', 200
    except Exception as e:
        raise e

gameover/api/templates/base.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}" />
		<link rel="stylesheet" href="{{ url_for('static', filename='css/login.css') }}" />
		<title>Gameover {% block title %}{% endblock %}</title>
	</head>
	<body class="app">
		<header class="header">
			<div class="header-item title">
				Gameover
			</div>
			<div class="header-item username">
				{{user.name}} {{user.surname}}
			</div>
		</header>
		
		<main class="main">
			{% block content %}{% endblock %}
		</main>
		
		<footer class="footer">
			<div class="header-item title">
				Footer
			</div>
			<div class="header-item">
				{{user.role}}
			</div>
		</footer>
	</body>
</html>

gameover/api/templates/index.html
{% extends "base.html" %}

{% block title %}
	{{title}}
{% endblock %}

{% block content %}

<div class="page-login">
<h1>
	{{msg}}
</h1>

<input  />
<br>
<input  />
<br>

<button class="btn-entrar">
	Entrar
</button>
<br>
<button class="btn-entrar">
	Criar conta
</button>


<ul>
	<li>{{user.name}}</li>
	<li>{{user.surname}}</li>
	<li>{{user.email}}</li>
</ul>

</div>

{% endblock %}

gameover/api/templates/login.html
{% extends "base.html" %}

{% block title %}
	{{title}}
{% endblock %}

{% block content %}
	<a href="{{url_for('Doc.index')}}">Home</a> 
	<form method="post" action="login" class="form-login">
	    <label for="username">E-mail</label>
	    <input name="email" id="email" required>
	    <br>
	    <label for="password">Senha</label>
	    <input type="password" name="password" id="password" required>
		<br>
		<button type="submit">
			Entrar
		</button>
		<br>
		<button>
			Criar conta
		</button>
	</form>
{% endblock %}